/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedUpgradeRouteImport } from './routes/_authenticated/upgrade'
import { Route as AuthenticatedTermsRouteImport } from './routes/_authenticated/terms'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedScannerRouteImport } from './routes/_authenticated/scanner'
import { Route as AuthenticatedPrivacyRouteImport } from './routes/_authenticated/privacy'
import { Route as AuthenticatedPositionsRouteImport } from './routes/_authenticated/positions'
import { Route as AuthenticatedMoversRouteImport } from './routes/_authenticated/movers'
import { Route as AuthenticatedHelpRouteImport } from './routes/_authenticated/help'
import { Route as AuthenticatedExitReplayRouteImport } from './routes/_authenticated/exit-replay'
import { Route as AuthenticatedCoinBotRouteImport } from './routes/_authenticated/coin-bot'
import { Route as AuthenticatedBotRouteImport } from './routes/_authenticated/bot'
import { Route as AuthenticatedBetaReportRouteImport } from './routes/_authenticated/beta-report'
import { Route as AuthenticatedAlgoConfigRouteImport } from './routes/_authenticated/algo-config'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAboutRouteImport } from './routes/_authenticated/about'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as ApiPublicHooksRefreshCoinUniverseRouteImport } from './routes/api/public/hooks/refresh-coin-universe'
import { Route as ApiPublicHooksMarkPositionsRouteImport } from './routes/api/public/hooks/mark-positions'
import { Route as ApiPublicHooksCoinScanRouteImport } from './routes/api/public/hooks/coin-scan'
import { Route as ApiPublicHooksBacktestRouteImport } from './routes/api/public/hooks/backtest'
import { Route as ApiPublicHooksAutoBookRouteImport } from './routes/api/public/hooks/auto-book'

const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUpgradeRoute = AuthenticatedUpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTermsRoute = AuthenticatedTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScannerRoute = AuthenticatedScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPrivacyRoute = AuthenticatedPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPositionsRoute = AuthenticatedPositionsRouteImport.update({
  id: '/positions',
  path: '/positions',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMoversRoute = AuthenticatedMoversRouteImport.update({
  id: '/movers',
  path: '/movers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHelpRoute = AuthenticatedHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExitReplayRoute = AuthenticatedExitReplayRouteImport.update({
  id: '/exit-replay',
  path: '/exit-replay',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCoinBotRoute = AuthenticatedCoinBotRouteImport.update({
  id: '/coin-bot',
  path: '/coin-bot',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBotRoute = AuthenticatedBotRouteImport.update({
  id: '/bot',
  path: '/bot',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBetaReportRoute = AuthenticatedBetaReportRouteImport.update({
  id: '/beta-report',
  path: '/beta-report',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAlgoConfigRoute = AuthenticatedAlgoConfigRouteImport.update({
  id: '/algo-config',
  path: '/algo-config',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAboutRoute = AuthenticatedAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksRefreshCoinUniverseRoute =
  ApiPublicHooksRefreshCoinUniverseRouteImport.update({
    id: '/api/public/hooks/refresh-coin-universe',
    path: '/api/public/hooks/refresh-coin-universe',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksMarkPositionsRoute =
  ApiPublicHooksMarkPositionsRouteImport.update({
    id: '/api/public/hooks/mark-positions',
    path: '/api/public/hooks/mark-positions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksCoinScanRoute = ApiPublicHooksCoinScanRouteImport.update({
  id: '/api/public/hooks/coin-scan',
  path: '/api/public/hooks/coin-scan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksBacktestRoute = ApiPublicHooksBacktestRouteImport.update({
  id: '/api/public/hooks/backtest',
  path: '/api/public/hooks/backtest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksAutoBookRoute = ApiPublicHooksAutoBookRouteImport.update({
  id: '/api/public/hooks/auto-book',
  path: '/api/public/hooks/auto-book',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/about': typeof AuthenticatedAboutRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/algo-config': typeof AuthenticatedAlgoConfigRoute
  '/beta-report': typeof AuthenticatedBetaReportRoute
  '/bot': typeof AuthenticatedBotRoute
  '/coin-bot': typeof AuthenticatedCoinBotRoute
  '/exit-replay': typeof AuthenticatedExitReplayRoute
  '/help': typeof AuthenticatedHelpRoute
  '/movers': typeof AuthenticatedMoversRoute
  '/positions': typeof AuthenticatedPositionsRoute
  '/privacy': typeof AuthenticatedPrivacyRoute
  '/scanner': typeof AuthenticatedScannerRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/terms': typeof AuthenticatedTermsRoute
  '/upgrade': typeof AuthenticatedUpgradeRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/hooks/auto-book': typeof ApiPublicHooksAutoBookRoute
  '/api/public/hooks/backtest': typeof ApiPublicHooksBacktestRoute
  '/api/public/hooks/coin-scan': typeof ApiPublicHooksCoinScanRoute
  '/api/public/hooks/mark-positions': typeof ApiPublicHooksMarkPositionsRoute
  '/api/public/hooks/refresh-coin-universe': typeof ApiPublicHooksRefreshCoinUniverseRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/about': typeof AuthenticatedAboutRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/algo-config': typeof AuthenticatedAlgoConfigRoute
  '/beta-report': typeof AuthenticatedBetaReportRoute
  '/bot': typeof AuthenticatedBotRoute
  '/coin-bot': typeof AuthenticatedCoinBotRoute
  '/exit-replay': typeof AuthenticatedExitReplayRoute
  '/help': typeof AuthenticatedHelpRoute
  '/movers': typeof AuthenticatedMoversRoute
  '/positions': typeof AuthenticatedPositionsRoute
  '/privacy': typeof AuthenticatedPrivacyRoute
  '/scanner': typeof AuthenticatedScannerRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/terms': typeof AuthenticatedTermsRoute
  '/upgrade': typeof AuthenticatedUpgradeRoute
  '/': typeof AuthenticatedIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/hooks/auto-book': typeof ApiPublicHooksAutoBookRoute
  '/api/public/hooks/backtest': typeof ApiPublicHooksBacktestRoute
  '/api/public/hooks/coin-scan': typeof ApiPublicHooksCoinScanRoute
  '/api/public/hooks/mark-positions': typeof ApiPublicHooksMarkPositionsRoute
  '/api/public/hooks/refresh-coin-universe': typeof ApiPublicHooksRefreshCoinUniverseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/about': typeof AuthenticatedAboutRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/algo-config': typeof AuthenticatedAlgoConfigRoute
  '/_authenticated/beta-report': typeof AuthenticatedBetaReportRoute
  '/_authenticated/bot': typeof AuthenticatedBotRoute
  '/_authenticated/coin-bot': typeof AuthenticatedCoinBotRoute
  '/_authenticated/exit-replay': typeof AuthenticatedExitReplayRoute
  '/_authenticated/help': typeof AuthenticatedHelpRoute
  '/_authenticated/movers': typeof AuthenticatedMoversRoute
  '/_authenticated/positions': typeof AuthenticatedPositionsRoute
  '/_authenticated/privacy': typeof AuthenticatedPrivacyRoute
  '/_authenticated/scanner': typeof AuthenticatedScannerRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/terms': typeof AuthenticatedTermsRoute
  '/_authenticated/upgrade': typeof AuthenticatedUpgradeRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/hooks/auto-book': typeof ApiPublicHooksAutoBookRoute
  '/api/public/hooks/backtest': typeof ApiPublicHooksBacktestRoute
  '/api/public/hooks/coin-scan': typeof ApiPublicHooksCoinScanRoute
  '/api/public/hooks/mark-positions': typeof ApiPublicHooksMarkPositionsRoute
  '/api/public/hooks/refresh-coin-universe': typeof ApiPublicHooksRefreshCoinUniverseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/about'
    | '/admin'
    | '/algo-config'
    | '/beta-report'
    | '/bot'
    | '/coin-bot'
    | '/exit-replay'
    | '/help'
    | '/movers'
    | '/positions'
    | '/privacy'
    | '/scanner'
    | '/settings'
    | '/terms'
    | '/upgrade'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/hooks/auto-book'
    | '/api/public/hooks/backtest'
    | '/api/public/hooks/coin-scan'
    | '/api/public/hooks/mark-positions'
    | '/api/public/hooks/refresh-coin-universe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/about'
    | '/admin'
    | '/algo-config'
    | '/beta-report'
    | '/bot'
    | '/coin-bot'
    | '/exit-replay'
    | '/help'
    | '/movers'
    | '/positions'
    | '/privacy'
    | '/scanner'
    | '/settings'
    | '/terms'
    | '/upgrade'
    | '/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/hooks/auto-book'
    | '/api/public/hooks/backtest'
    | '/api/public/hooks/coin-scan'
    | '/api/public/hooks/mark-positions'
    | '/api/public/hooks/refresh-coin-universe'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/about'
    | '/_authenticated/admin'
    | '/_authenticated/algo-config'
    | '/_authenticated/beta-report'
    | '/_authenticated/bot'
    | '/_authenticated/coin-bot'
    | '/_authenticated/exit-replay'
    | '/_authenticated/help'
    | '/_authenticated/movers'
    | '/_authenticated/positions'
    | '/_authenticated/privacy'
    | '/_authenticated/scanner'
    | '/_authenticated/settings'
    | '/_authenticated/terms'
    | '/_authenticated/upgrade'
    | '/_authenticated/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/hooks/auto-book'
    | '/api/public/hooks/backtest'
    | '/api/public/hooks/coin-scan'
    | '/api/public/hooks/mark-positions'
    | '/api/public/hooks/refresh-coin-universe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  McpRoute: typeof McpRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicHooksAutoBookRoute: typeof ApiPublicHooksAutoBookRoute
  ApiPublicHooksBacktestRoute: typeof ApiPublicHooksBacktestRoute
  ApiPublicHooksCoinScanRoute: typeof ApiPublicHooksCoinScanRoute
  ApiPublicHooksMarkPositionsRoute: typeof ApiPublicHooksMarkPositionsRoute
  ApiPublicHooksRefreshCoinUniverseRoute: typeof ApiPublicHooksRefreshCoinUniverseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/upgrade': {
      id: '/_authenticated/upgrade'
      path: '/upgrade'
      fullPath: '/upgrade'
      preLoaderRoute: typeof AuthenticatedUpgradeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/terms': {
      id: '/_authenticated/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof AuthenticatedTermsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scanner': {
      id: '/_authenticated/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof AuthenticatedScannerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/privacy': {
      id: '/_authenticated/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof AuthenticatedPrivacyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/positions': {
      id: '/_authenticated/positions'
      path: '/positions'
      fullPath: '/positions'
      preLoaderRoute: typeof AuthenticatedPositionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/movers': {
      id: '/_authenticated/movers'
      path: '/movers'
      fullPath: '/movers'
      preLoaderRoute: typeof AuthenticatedMoversRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help': {
      id: '/_authenticated/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AuthenticatedHelpRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exit-replay': {
      id: '/_authenticated/exit-replay'
      path: '/exit-replay'
      fullPath: '/exit-replay'
      preLoaderRoute: typeof AuthenticatedExitReplayRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/coin-bot': {
      id: '/_authenticated/coin-bot'
      path: '/coin-bot'
      fullPath: '/coin-bot'
      preLoaderRoute: typeof AuthenticatedCoinBotRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bot': {
      id: '/_authenticated/bot'
      path: '/bot'
      fullPath: '/bot'
      preLoaderRoute: typeof AuthenticatedBotRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/beta-report': {
      id: '/_authenticated/beta-report'
      path: '/beta-report'
      fullPath: '/beta-report'
      preLoaderRoute: typeof AuthenticatedBetaReportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/algo-config': {
      id: '/_authenticated/algo-config'
      path: '/algo-config'
      fullPath: '/algo-config'
      preLoaderRoute: typeof AuthenticatedAlgoConfigRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/about': {
      id: '/_authenticated/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AuthenticatedAboutRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/refresh-coin-universe': {
      id: '/api/public/hooks/refresh-coin-universe'
      path: '/api/public/hooks/refresh-coin-universe'
      fullPath: '/api/public/hooks/refresh-coin-universe'
      preLoaderRoute: typeof ApiPublicHooksRefreshCoinUniverseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/mark-positions': {
      id: '/api/public/hooks/mark-positions'
      path: '/api/public/hooks/mark-positions'
      fullPath: '/api/public/hooks/mark-positions'
      preLoaderRoute: typeof ApiPublicHooksMarkPositionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/coin-scan': {
      id: '/api/public/hooks/coin-scan'
      path: '/api/public/hooks/coin-scan'
      fullPath: '/api/public/hooks/coin-scan'
      preLoaderRoute: typeof ApiPublicHooksCoinScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/backtest': {
      id: '/api/public/hooks/backtest'
      path: '/api/public/hooks/backtest'
      fullPath: '/api/public/hooks/backtest'
      preLoaderRoute: typeof ApiPublicHooksBacktestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/auto-book': {
      id: '/api/public/hooks/auto-book'
      path: '/api/public/hooks/auto-book'
      fullPath: '/api/public/hooks/auto-book'
      preLoaderRoute: typeof ApiPublicHooksAutoBookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAboutRoute: typeof AuthenticatedAboutRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAlgoConfigRoute: typeof AuthenticatedAlgoConfigRoute
  AuthenticatedBetaReportRoute: typeof AuthenticatedBetaReportRoute
  AuthenticatedBotRoute: typeof AuthenticatedBotRoute
  AuthenticatedCoinBotRoute: typeof AuthenticatedCoinBotRoute
  AuthenticatedExitReplayRoute: typeof AuthenticatedExitReplayRoute
  AuthenticatedHelpRoute: typeof AuthenticatedHelpRoute
  AuthenticatedMoversRoute: typeof AuthenticatedMoversRoute
  AuthenticatedPositionsRoute: typeof AuthenticatedPositionsRoute
  AuthenticatedPrivacyRoute: typeof AuthenticatedPrivacyRoute
  AuthenticatedScannerRoute: typeof AuthenticatedScannerRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTermsRoute: typeof AuthenticatedTermsRoute
  AuthenticatedUpgradeRoute: typeof AuthenticatedUpgradeRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAboutRoute: AuthenticatedAboutRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAlgoConfigRoute: AuthenticatedAlgoConfigRoute,
  AuthenticatedBetaReportRoute: AuthenticatedBetaReportRoute,
  AuthenticatedBotRoute: AuthenticatedBotRoute,
  AuthenticatedCoinBotRoute: AuthenticatedCoinBotRoute,
  AuthenticatedExitReplayRoute: AuthenticatedExitReplayRoute,
  AuthenticatedHelpRoute: AuthenticatedHelpRoute,
  AuthenticatedMoversRoute: AuthenticatedMoversRoute,
  AuthenticatedPositionsRoute: AuthenticatedPositionsRoute,
  AuthenticatedPrivacyRoute: AuthenticatedPrivacyRoute,
  AuthenticatedScannerRoute: AuthenticatedScannerRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTermsRoute: AuthenticatedTermsRoute,
  AuthenticatedUpgradeRoute: AuthenticatedUpgradeRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  McpRoute: McpRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicHooksAutoBookRoute: ApiPublicHooksAutoBookRoute,
  ApiPublicHooksBacktestRoute: ApiPublicHooksBacktestRoute,
  ApiPublicHooksCoinScanRoute: ApiPublicHooksCoinScanRoute,
  ApiPublicHooksMarkPositionsRoute: ApiPublicHooksMarkPositionsRoute,
  ApiPublicHooksRefreshCoinUniverseRoute:
    ApiPublicHooksRefreshCoinUniverseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
