/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedScannerRouteImport } from './routes/_authenticated/scanner'
import { Route as AuthenticatedPositionsRouteImport } from './routes/_authenticated/positions'
import { Route as AuthenticatedMoversRouteImport } from './routes/_authenticated/movers'
import { Route as AuthenticatedHelpRouteImport } from './routes/_authenticated/help'
import { Route as ApiPublicHooksMarkPositionsRouteImport } from './routes/api/public/hooks/mark-positions'
import { Route as ApiPublicHooksAutoBookRouteImport } from './routes/api/public/hooks/auto-book'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScannerRoute = AuthenticatedScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPositionsRoute = AuthenticatedPositionsRouteImport.update({
  id: '/positions',
  path: '/positions',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMoversRoute = AuthenticatedMoversRouteImport.update({
  id: '/movers',
  path: '/movers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHelpRoute = AuthenticatedHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicHooksMarkPositionsRoute =
  ApiPublicHooksMarkPositionsRouteImport.update({
    id: '/api/public/hooks/mark-positions',
    path: '/api/public/hooks/mark-positions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAutoBookRoute = ApiPublicHooksAutoBookRouteImport.update({
  id: '/api/public/hooks/auto-book',
  path: '/api/public/hooks/auto-book',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/help': typeof AuthenticatedHelpRoute
  '/movers': typeof AuthenticatedMoversRoute
  '/positions': typeof AuthenticatedPositionsRoute
  '/scanner': typeof AuthenticatedScannerRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/public/hooks/auto-book': typeof ApiPublicHooksAutoBookRoute
  '/api/public/hooks/mark-positions': typeof ApiPublicHooksMarkPositionsRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/help': typeof AuthenticatedHelpRoute
  '/movers': typeof AuthenticatedMoversRoute
  '/positions': typeof AuthenticatedPositionsRoute
  '/scanner': typeof AuthenticatedScannerRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/': typeof AuthenticatedIndexRoute
  '/api/public/hooks/auto-book': typeof ApiPublicHooksAutoBookRoute
  '/api/public/hooks/mark-positions': typeof ApiPublicHooksMarkPositionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/help': typeof AuthenticatedHelpRoute
  '/_authenticated/movers': typeof AuthenticatedMoversRoute
  '/_authenticated/positions': typeof AuthenticatedPositionsRoute
  '/_authenticated/scanner': typeof AuthenticatedScannerRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/api/public/hooks/auto-book': typeof ApiPublicHooksAutoBookRoute
  '/api/public/hooks/mark-positions': typeof ApiPublicHooksMarkPositionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/help'
    | '/movers'
    | '/positions'
    | '/scanner'
    | '/settings'
    | '/api/public/hooks/auto-book'
    | '/api/public/hooks/mark-positions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/help'
    | '/movers'
    | '/positions'
    | '/scanner'
    | '/settings'
    | '/'
    | '/api/public/hooks/auto-book'
    | '/api/public/hooks/mark-positions'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/help'
    | '/_authenticated/movers'
    | '/_authenticated/positions'
    | '/_authenticated/scanner'
    | '/_authenticated/settings'
    | '/_authenticated/'
    | '/api/public/hooks/auto-book'
    | '/api/public/hooks/mark-positions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicHooksAutoBookRoute: typeof ApiPublicHooksAutoBookRoute
  ApiPublicHooksMarkPositionsRoute: typeof ApiPublicHooksMarkPositionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scanner': {
      id: '/_authenticated/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof AuthenticatedScannerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/positions': {
      id: '/_authenticated/positions'
      path: '/positions'
      fullPath: '/positions'
      preLoaderRoute: typeof AuthenticatedPositionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/movers': {
      id: '/_authenticated/movers'
      path: '/movers'
      fullPath: '/movers'
      preLoaderRoute: typeof AuthenticatedMoversRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help': {
      id: '/_authenticated/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AuthenticatedHelpRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/mark-positions': {
      id: '/api/public/hooks/mark-positions'
      path: '/api/public/hooks/mark-positions'
      fullPath: '/api/public/hooks/mark-positions'
      preLoaderRoute: typeof ApiPublicHooksMarkPositionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/auto-book': {
      id: '/api/public/hooks/auto-book'
      path: '/api/public/hooks/auto-book'
      fullPath: '/api/public/hooks/auto-book'
      preLoaderRoute: typeof ApiPublicHooksAutoBookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedHelpRoute: typeof AuthenticatedHelpRoute
  AuthenticatedMoversRoute: typeof AuthenticatedMoversRoute
  AuthenticatedPositionsRoute: typeof AuthenticatedPositionsRoute
  AuthenticatedScannerRoute: typeof AuthenticatedScannerRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedHelpRoute: AuthenticatedHelpRoute,
  AuthenticatedMoversRoute: AuthenticatedMoversRoute,
  AuthenticatedPositionsRoute: AuthenticatedPositionsRoute,
  AuthenticatedScannerRoute: AuthenticatedScannerRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicHooksAutoBookRoute: ApiPublicHooksAutoBookRoute,
  ApiPublicHooksMarkPositionsRoute: ApiPublicHooksMarkPositionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
